# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cosmin Trăistaru
email: Cosmin @ Traista . ru
description: "Personal Website/blog/something. Just trying stuff out."

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cosmin.traista.ru" # the base hostname & protocol for your site
github_username: CosminTraistaru
twitter_username: CosminTraistaru

author:
  name: Cosmin Trăistaru
  github: CosminTraistaru
  github_url: https://github.com/CosminTraistaru
  facebook_url: https://www.facebook.com/cosmin.traistaru
  linkedin_url: https://ro.linkedin.com/in/cosmintraistaru
  googleplus_url: https://plus.google.com/+CosminTraistaru/


facebook:
  admins: CosminTrăistaru
  publisher: https://fb.com/CosminTraistaru
  app_id: 299475630067491

google_site_verification: YrB36JwKLcBsz30KxJJDQaIMXIXwCZ20znMwb6vsj3A

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
